### ISSUE TITLE
Dictionaries not found

### ISSUE THREAD

**Issue by tibcal** [jupyterlab-contrib/spellchecker#80] opened 2021-07-09 13:11 UTC
Hello,
First of all, thank you for this project. I've install spellchecker, with no errors. But when launching jupyter lab, dictionaries are not found, although the repertory "dictionaries" is create in the right place during installation.

Output of the terminal :
[W 2021-07-09 15:02:51.717 ServerApp] 404 GET /spellchecker/language_manager?1625835770998 (127.0.0.1) 542.53ms referer=http://localhost:8888/lab

System : Fedora

**Comment by krassowski** [comment] 2021-07-09 13:27
It looks like the server extension is not enabled/installed properly. Could you provide the output of the following commands, please:

```
jupyter serverextension list
```

and:

```
# note the extra space
jupyter server extension list
```

and

```
jupyter lab --version
```

and

```
pip list | grep jupyter-server
```

**Comment by tibcal** [comment] 2021-07-09 13:46
No output for `jupyter serverextension list`
Output of `jupyter server extension list` : 
```
Config dir: /home/thibaut/.jupyter

Config dir: /usr/etc/jupyter

Config dir: /usr/local/etc/jupyter
```
Output of `jupyter lab --version` : `3.0.5`

Output of 'pip list | grep jupyter-server' :` jupyter-server                    1.2.2
`

**Comment by krassowski** [comment] 2021-07-09 13:49
How did you install the spellchecker extension?

**Comment by tibcal** [comment] 2021-07-09 13:52
First of all via the extension manager (web interface), but I've got errors when building jupyter lab after installation. Then I tried and managed to install via pip.

**Comment by krassowski** [comment] 2021-07-09 13:55
Could you please try running:

```
jupyter serverextension enable jupyterlab_spellchecker
```

and let me know what is the output (and if it ends with "OK", if it the spellchecker is now working after restarting JupyterLab).

Also, I would recommend upgrading JupterLab (current is 3.0.16), upgrading jupyter-server (current is 1.9.0).

**Comment by tibcal** [comment] 2021-07-09 14:29
I've upgraded jupyterlab and jupyter-server, and try `jupyter serverextension enable jupyterlab_spellchecker`. Output is OK, but spellchecker is still not working.

**Comment by krassowski** [comment] 2021-07-09 14:30
What is the output of

```
jupyter serverextension list
```

this time?

**Comment by krassowski** [comment] 2021-07-09 14:32
Maybe there is something relevant in logs when starting with `jupterlab --debug`?

**Comment by tibcal** [comment] 2021-07-09 14:37
Output of` jupyter serverextension list` :
```
config dir: /home/thibaut/.jupyter
    jupyterlab_spellchecker  enabled 
    - Validating...
      jupyterlab_spellchecker 0.6.0 OK
```
With debug, nothing more about spellshecker than :
`[W 2021-07-09 16:33:08.313 ServerApp] 404 GET /spellchecker/language_manager?1625841188122 (127.0.0.1) 17.71ms referer=http://localhost:8888/lab`

**Comment by krassowski** [comment] 2021-07-09 14:48
Well there should be:

```
[I 2021-07-09 15:46:07.746 ServerApp] jupyterlab_spellchecker | extension was successfully linked.
```

at the very top. I am running out of ideas, sorry :(

Are you maybe starting jupyterlab as a root (with sudo?). Do you have any extra configuration options enabled?

**Comment by tibcal** [comment] 2021-07-09 15:22
I've uninstalled then reinstalled jupyter lab, and it's finally working ! Thanks for your help.

**Comment by krassowski** [comment] 2021-07-09 15:32
That's great, I'm glad it is working now! I will close this issue, but if you encounter this problem again and get to narrowing down the cause please feel free to share it here.

**Closed by krassowski** 2021-07-09 15:32 UTC

**Comment by smirnovskysaha** [comment] 2021-08-17 06:28
Hello, Michał,

I have exactly the same problem as tibcal.  

Spellchecker does not work, output in the terminal:  
`[W 2021-08-16 21:17:06.619 ServerApp] 404 GET /spellchecker/language_manager?1629137825397 (::1) 40.85ms referer=http://localhost:8888/lab`

```
jupyter serverextension list
config dir: /home/saha/.jupyter
    jupyter_nbextensions_configurator  enabled 
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 OK
    jupyterlab_spellchecker  enabled 
    - Validating...
      jupyterlab_spellchecker 0.7.0 OK
config dir: /usr/etc/jupyter
    ipyparallel.nbextension  enabled 
    - Validating...
      ipyparallel.nbextension  OK
```

```
jupyter server extension list
Config dir: /home/saha/.jupyter

Config dir: /usr/etc/jupyter

Config dir: /usr/local/etc/jupyter
```

```
pip list | grep jupyter
jupyter                           1.1.0
jupyter-client                    6.1.12
jupyter-console                   6.4.0
jupyter-contrib-core              0.3.3
jupyter-core                      4.7.1
jupyter-highlight-selected-word   0.2.0
jupyter-latex-envs                1.4.6
jupyter-nbextensions-configurator 0.4.1
jupyter-server                    1.10.2
jupyterlab                        3.1.7
jupyterlab-language-pack-ru-RU    0.0.2.dev0
jupyterlab-pygments               0.1.2
jupyterlab-server                 2.7.0
jupyterlab-spellchecker           0.7.0
```

Maybe there is some conflict with different versions of jupyter components?  
Is there a way to debug the spellchecker extension?

I use Gentoo.

**Comment by smirnovskysaha** [comment] 2021-08-17 13:48
It seems that jupyterlab_spellchecker extension is not loading properly during jupyterlab startup. When I interrupt jupyterlab by Ctrl+C, it outputs that "Shutting down 1 extension" (this extension is jupyterlab; at startup log output contains "JupyterLab extension loaded from /home/saha/.local/lib/python3.9/site-packages/jupyterlab")

**Comment by krassowski** [comment] 2021-08-17 14:22
Hi @smirnovskysaha,

your `jupyter server extension list` result is empty - it means that the extension is not enabled for JupyterLab 3 ([see this explanation](https://stackoverflow.com/a/67804732/6646912)).

Please run the following command:

```
jupyter server extension enable jupyterlab_spellchecker
```

and again run:

```
jupyter server extension list
```

Please let me know what is the output and if the spellchecker starts working for you after that.

**Comment by smirnovskysaha** [comment] 2021-08-17 16:06
@krassowski, thank you very much!

In my case the proper command to enable the extension was
```
jupyter server extension enable --user jupyterlab_spellchecker
```
till I do not use system-wide installation of JupyterLab.

Now the extension works great!

**Comment by krassowski** [comment] 2021-08-17 17:51
That's great to hear, thank you for getting back to us and leaving this hint!

We generally recommend using virtual environments where adding `--user` is not needed, but indeed once you start using `--user` you need to be careful to always remember to add it.
